name: Perl Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
 
jobs:
  perl-job:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        perl-version:
          - '5.36'
          - '5.38'
          - 'latest'
    
    runs-on: ${{ matrix.os }}
    name: Perl ${{ matrix.perl-version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry  # Provides better Windows compatibility if needed

      - name: Install Dependencies
        run: |
          cpanm --notest Dist::Zilla
          cpanm --notest App::cpanminus
          dzil authordeps --missing | cpanm --notest
          dzil listdeps --author --missing | cpanm --notest

      - name: Run Tests
        run: |
          dzil test --verbose

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-perl-${{ matrix.perl-version }}
          path: |
            ./*.log
            ./test-*.tar.gz
          retention-days: 7